#pragma once

#include <unordered_map>

#include "optimization.hpp"

class Assembler {
public:
    Assembler(std::vector<Pattern> patterns, bool use_hexagon_alternatives);

    std::string assemble();
private:
    const std::string m_pattern_strings[PatternType::num_patterns] = {
        "Akasha's Distillation",
        "Akasha's Gambit",
        "Altiora",
        "Additive Distillation",
        "Alidade's Purification",
        "Anchorite's Flight",
        "Archer's Distillation",
        "Architect's Distillation",
        "Arc's Reflection",
        "Augur's Exaltation",
        "Augur's Purification",
        "Auditor's Purification",
        "Auditor's Reflection",
        "Assessor's Purification",
        "Assessor's Reflection",
        "Aviator's Purification",
        "Banish Sentinel",
        "Axial Purification",
        "Black Sun's Nadir",
        "Black Sun's Zenith",
        "Blink",
        "Blue Sun's Nadir",
        "Blue Sun's Zenith",
        "Bookkeeper's Gambit",
        "Break Block",
        "Ceiling Purification",
        "Charon's Gambit",
        "Caster's Glamour",
        "Chronicler's Gambit",
        "Chronicler's Purification",
        "Circle's Reflection",
        "Compass' Purification",
        "Compass' Purification II",
        "Conjunction Distillation",
        "Conjure Light",
        "Conjure Block",
        "Consideration",
        "Cosine Purification",
        "Craft Artifact",
        "Craft Cypher",
        "Craft Trinket",
        "Craft Phial",
        "Create Water",
        "Create Lava",
        "Derivation Decomposition",
        "Destroy Liquid",
        "Dioscuri Gambit",
        "Disjunction Distillation",
        "Division Distillation",
        "Dispel Rain",
        "Entropy Reflection",
        "Euler's Reflection",
        "Edify Sapling",
        "Entity Purification",
        "Entity Purification: Animal",
        "Entity Purification: Item",
        "Entity Purification: Living",
        "Entity Purification: Monster",
        "Entity Purification: Player",
        "Equality Distillation",
        "Erase Item",
        "Extinguish Area",
        "Excisor's Distillation",
        "Exclusion Distillation",
        "Explosion",
        "False Reflection",
        "Fireball",
        "Fisherman's Gambit",
        "Fisherman's Gambit II",
        "Flock's Disintegration",
        "Flock's Gambit",
        "Flock's Reflection",
        "Flay Mind",
        "Floor Purification",
        "Gemini Decomposition",
        "Gemini Gambit",
        "Green Sun's Nadir",
        "Green Sun's Zenith",
        "Greater Fold Reflection",
        "Greater Teleport",
        "Hermes' Gambit",
        "Huginn's Gambit",
        "Ignite",
        "Inequality Distillation",
        "Impulse",
        "Integration Distillation",
        "Inverse Cosine Purification",
        "Inverse Sine Purification",
        "Inverse Tangent Distillation",
        "Inverse Tangent Purification",
        "Internalize Pigment",
        "{",
        "Iris' Gambit",
        "Jester's Gambit",
        "Length Purification",
        "Locate Sentinel",
        "Lesser Fold Reflection",
        "Locator's Distillation",
        "Lodestone Reflection",
        "Logarithmic Distillation",
        "Make Note",
        "Maximus Distillation",
        "Maximus Distillation II",
        "Mind's Reflection",
        "Minimus Distillation",
        "Minimus Distillation II",
        "Modulus Distillation",
        "Multiplicative Distillation",
        "Muninn's Reflection",
        "Negation Purification",
        "Nullary Reflection",
        "Numerical Reflection",
        "Overgrow",
        "Pace Purification",
        "Place Block",
        "Power Distillation",
        "Prospector's Gambit",
        "Retrograde Purification",
        "Recharge Item",
        "}",
        "Reveal",
        "Red Sun's Nadir",
        "Red Sun's Zenith",
        "Rotation Gambit",
        "Rotation Gambit II",
        "Scout's Distillation",
        "Scribe's Gambit",
        "Scribe's Reflection",
        "Selection Distillation",
        "Selection Exaltation",
        "Speaker's Decomposition",
        "Speaker's Distillation",
        "Single's Purification",
        "Stadiometer's Purification",
        "Subtractive Distillation",
        "Sine Purification",
        "Swindler's Gambit",
        "Summon Lightning",
        "Summon Rain",
        "Summon Greater Sentinel",
        "Summon Sentinel",
        "Surgeon's Exaltation",
        "Tangent Purification",
        "Thanatos' Reflection",
        "Thoth's Gambit",
        "True Reflection",
        "Uniqueness Purification",
        "Vacant Reflection",
        "Vector Disintegration",
        "Vector Exaltation",
        "Vector Reflection -X",
        "Vector Reflection -Y",
        "Vector Reflection -Z",
        "Vector Reflection +X",
        "Vector Reflection +Y",
        "Vector Reflection +Z",
        "Vector Reflection Zero",
        "Wayfarer's Flight",
        "Wayfind Sentinel",
        "Waystone Reflection",
        "White Sun's Nadir",
        "White Sun's Zenith",
        "Zone Distillation: Animal",
        "Zone Distillation: Any",
        "Zone Distillation: Item",
        "Zone Distillation: Living",
        "Zone Distillation: Monster",
        "Zone Distillation: Non-Animal",
        "Zone Distillation: Non-Item",
        "Zone Distillation: Non-Living",
        "Zone Distillation: Non-Monster",
        "Zone Distillation: Non-Player",
        "Zone Distillation: Player"
    };

    const std::unordered_map<PatternType, std::string> m_hexagon_alternatives = {
        {PatternType::derivation_decomposition, "Combination Distillation"},
    };

    bool m_using_hexagon;

    std::vector<Pattern> m_patterns;

    int m_indent_level = 0;
};